### ISSUE TITLE
Add Store

### ISSUE THREAD

**Issue by maltegrosse** [fschuetz04/simgo#3]
Dear Felix,

thank you for your great work porting SimPy to Golang.

Is it possible to add the simple Store , like @peterjrichens implemented:
https://github.com/peterjrichens/simgo/blob/main/store.go

**Comment by fschuetz04** [comment]
Hi @maltegrosse, I implemented a simple store in here: https://github.com/fschuetz04/simgo/blob/main/store.go. Usage should be similar to @peterjrichens solution:

```go
sim := &Simulation{}
store := NewStoreWithCapacity[int](sim, 1)

sim.Process(func(proc Process) {
  proc.Wait(store.Put(42))
  ev := store.Get()
  proc.Wait(ev)
  fmt.Println(ev.Item)
})

sim.Run()
```

Please test and report whether it works for you.

**Comment by maltegrosse** [comment]
@fschuetz04 
Thank you! I will test it next year as I am currently in a middle of a development where I got  @peterjrichens solution working.
(and i dont wanna break anything :-)
